### Test find all classOrders
GET http://localhost:8080/classOrder
Content-Type: application/json


### Test find classOrders by id
GET http://localhost:8080/classOrder/4
Content-Type: application/json

### Test insert classOrder
POST http://localhost:8080/classOrder
Content-Type: application/json

{
  "idClassOrder": 2,
  "dsClassOrder": "Classe Test 1",
  "phylum":{
    "idPhylum": 1
  }
}

### Test update classOrder
PUT http://localhost:8080/classOrder
Content-Type: application/json

{
  "idClassOrder": 4,
  "dsClassOrder": "Classe Test 1234",
  "phylum": {
    "idPhylum": 1,
    "dsPhylum": "Filo Test 2"
  }
}

### Test delete classOrders by id
DELETE http://localhost:8080/classOrder/4
Content-Type: application/json